name: Version Bump and Release

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: write  # Allows the workflow to create tags and releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run version bump and release action
        uses: HafslundEcoVannkraft/stratus-gh-actions/.github/actions/release@v0.1.0           
        with:
          draft: "false"
          prerelease: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}