name: Draft Release
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  call-draft-release:
    uses: HafslundEcoVannkraft/stratus-gh-actions/.github/workflows/reusable-draft-release.yml@v1.1.0
    secrets: inherit
